language: 'elixir'

elixir: 1.10.2
otp_release: 22.0.7

matrix:
  include:
  - otp_release: 21.3
    elixir: 1.8.1
  - otp_release: 22.0.7
    elixir: 1.9.4
  - otp_release: 22.3.4
    elixir: 1.10.2
  - otp_release: 23.0.2
    elixir: 1.11.3

cache:
  directories:
  - _build
  - deps

env:
  global:
    - MIX_ENV: 'test'

script:
  - ./ci-check.sh
  - mix coveralls.travis
